- name: install nginx server and run
  hosts: nginx #give nginx private ip
  #hosts: all
  become: yes #take sudo access
  serial: 3
  tasks: 
  - name: install nginx
    ansible.builtin.package:  #hetrogeneous module that can work for all distributions like ubuntu, linux, redhat
     name: nginx
     state: present

  - name: Start nginx
    ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes